- README.md
> Update readme: Add link to PGP key for contact email address

- bin/src/check.rs
- bin/src/config.rs
- bin/src/daemon.rs
- bin/src/diag.rs
- bin/src/server.rs
- lib/src/analysis/analyzer.rs
- lib/src/analysis/connection_redirect_downgrade.rs
- lib/src/analysis/imsi_requested.rs
- lib/src/analysis/null_cipher.rs
- rootshell/src/main.rs
This PR contains fixes for several clippy warnings. I have not fixed warnings that might change the function of the code to fix, and those that are more stylistic in nature.
> Clippy fixes

- .github/workflows/build-release.yml
- dist/install.sh
Turns out we were wrong, there is a free macOS Intel Github runner!
> Build macOS Intel release artifacts

- bin/static/js/main.js
> Fix web UI

- bin/Cargo.toml
we uhh forgot to do this for every release lol
> bump version number

- bin/src/analysis.rs
- bin/src/daemon.rs
- bin/src/dummy_analyzer.rs
- bin/src/qmdl_store.rs
- lib/src/analysis/analyzer.rs
- lib/src/analysis/connection_redirect_downgrade.rs
- lib/src/analysis/imsi_provided.rs
- lib/src/analysis/imsi_requested.rs
- lib/src/analysis/information_element.rs
- lib/src/analysis/null_cipher.rs
- lib/src/analysis/priority_2g_downgrade.rs
- lib/src/diag.rs
- lib/src/util.rs
This PR fixes even more clippy warnings! See commit messages for the details of each change.
> More clippy fixes

- README.md
> Improve installation doc clarity. Cleanup capitalization. Fixed #169 

- .github/workflows/ISSUE_TEMPLATE/bug.yaml
- .github/workflows/ISSUE_TEMPLATE/config.yaml
- .github/workflows/ISSUE_TEMPLATE/feature.yaml
Take it or leave it. Figure it might help with triage. :)
> [REPO] Add Issue Templates

- bin/src/qmdl_store.rs
> Fix RecordingStore::create

- dist/install.sh
> mac installer: if we've already removed quarantine bit, continue

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
Issue templates are in the wrong spot, apologies
> [REPO] Move Templates to Correct Location

- README.md
Fix https://github.com/EFForg/rayhunter/issues/134
> Document what the red line means

- .github/workflows/build-release.yml
should fix the build failure in `main`
> ci: add windows target for serial

- bin/src/daemon.rs
- bin/src/qmdl_store.rs
* Delete All Recordings did not work when recording was paused
* Because of the upgrade to axum 0.8 in #235, the webserver did not actually
start but panic.
> Fix delete all recordings, and panic on server startup

- README.md
Apparently SD card is not a thing on Orbic, only on TP-Link.
> README: Do not mention SD card

- README.md
> unzip -> decompress

- README.md
Had to check around forums and docs just to find this info so just dumped here. Take it or leave it though if this exists somewhere else.
Also, are WiFi bands needed? Probably not but left it just in case.
> [DOCS] Update README.md to Explicitly State Supported Bands

- doc/SUMMARY.md
- doc/orbic.md
- doc/supported-devices.md
- doc/tplink-m7350.md
> Add basic docs for TP-Link

- doc/SUMMARY.md
> Fix typo in SUMMARY.md

- doc/installing-from-release.md
- doc/installing-from-source.md
- doc/tplink-m7350.md
- doc/using-rayhunter.md
mostly updates for tplink since the usage docs are slightly wrong for it.
depends on #291
> Update documentation for Rust installer

- doc/installing-from-release-windows.md
- installer/install.ps1
> fix issues with powershell installer

- doc/installing-from-release.md
> [DOCS] Fix install extract instructions

- bin/src/qmdl_store.rs
For some reason, some QMDL files are missing on my device. In this
situation Delete All Recordings should not fail on the first missing
file.
> Make Delete All Recordings more robust against missing recordings

- Cargo.lock
- installer/Cargo.toml
- installer/src/main.rs
Some libraries, namely nusb, produce debug logging that we might want to access in the field.
> Add env_logger to installer

- doc/installing-from-release.md
> Mention quarantine bit on macOS

- doc/installing-from-release-windows.md
- installer/src/orbic.rs
> update win docs

- Cargo.lock
- bin/Cargo.toml
- installer/Cargo.toml
- lib/Cargo.toml
- make.sh
- rootshell/Cargo.toml
- telcom-parser/Cargo.toml
> Version bump

- Cargo.lock
- installer/Cargo.toml
> Switch to the EFF org fork of adb_client

- Cargo.lock
- bin/Cargo.toml
- installer/Cargo.toml
- lib/Cargo.toml
- rootshell/Cargo.toml
- telcom-parser/Cargo.toml
> bump version

- doc/installing-from-release.md
> doc: Fix instructions for mac quarantine bit

- bin/src/key_input.rs
> Debounce key input events

- .github/workflows/main.yml
- bin/web/svelte.config.js
Hopefully this and #415 can reduce the pain coming from telcom-parser compile times (see https://github.com/EFForg/rayhunter/issues/377)
> Try out rust-cache action

- doc/SUMMARY.md
- doc/installing-from-release.md
- doc/supported-devices.md
- doc/wingtech-ct2mhs01.md
Add documentation for the Wingtech CT2MHS01 hotspot.
> doc: Wingtech CT2MHS01

- daemon/web/src/lib/components/ConfigForm.svelte
- daemon/web/src/lib/utils.svelte.ts
- dist/config.toml.example
- doc/heuristics.md
- lib/src/analysis/analyzer.rs
- lib/src/analysis/mod.rs
- lib/src/analysis/nas_null_cipher.rs
look for null cipher request in NAS messages.
> NAS nullcipher

- lib/src/analysis/imsi_requested.rs
Add attach complete to remove a false positive
> Attach type

- daemon/src/diag.rs
- daemon/src/qmdl_store.rs
> Fixes #433 do not stop recording when deleting a past entry

- .gitattributes
> Fix line endings on Windows

- .github/ISSUE_TEMPLATE/installer-bug.yaml
For installer issues there is a different set of questions we want to user to answer so having a specific issue template for these makes sense.
> Add an issue template for Installer issues

- .github/ISSUE_TEMPLATE/installer-bug.yaml
- doc/installing-from-release-windows.md
- doc/installing-from-release.md
- installer/src/tplink.rs
The current error message is not very useful for remote-debugging. Add
enough context to allow technically adept users to figure out a way.
See #544
> Fix issue template, mention sdcard in the docs and improve one error message

- daemon/src/battery/mod.rs
- daemon/src/battery/orbic.rs
- daemon/src/battery/tmobile.rs
- daemon/src/battery/wingtech.rs
- daemon/src/error.rs
- daemon/src/main.rs
- daemon/src/stats.rs
- daemon/web/src/lib/components/SystemStatsTable.svelte
- daemon/web/src/lib/systemStats.ts
> Add battery level to web UI

- daemon/src/main.rs
- daemon/src/stats.rs
- daemon/web/src/app.html
- daemon/web/src/lib/components/LogView.svelte
- daemon/web/src/lib/utils.svelte.ts
- daemon/web/src/routes/+page.svelte
This PR adds a log view modal that looks like this:
Opened via a new top bar button:
> Add log view to web UI

- lib/src/analysis/analyzer.rs
- lib/src/analysis/connection_redirect_downgrade.rs
- lib/src/analysis/imsi_requested.rs
- lib/src/analysis/incomplete_sib.rs
- lib/src/analysis/nas_null_cipher.rs
- lib/src/analysis/null_cipher.rs
- lib/src/analysis/priority_2g_downgrade.rs
- lib/src/analysis/test_analyzer.rs
fixes https://github.com/EFForg/rayhunter/issues/475 and fixes https://github.com/EFForg/rayhunter/issues/556
> track packet num in analysis harness

- daemon/src/battery/mod.rs
- daemon/src/battery/tplink.rs
First draft of battery support for TPlink using `uci`.  Tested on v9.
Would appreciate feedback on the code as I’m still a bit of a rust noob.
> tplink: Implement battery level support

- daemon/web/.gitignore
- daemon/web/package-lock.json
It seems we never checked in our package-lock.json, which means there's
no effective checksum verification or version pinning going on.
> Check in package-lock.json
