lib/src/analysis/analyzer.rs, lib/src/analysis/imsi_provided.rs, lib/src/analysis/mod.rs, lib/src/analysis/null_cipher.rs, tools/README.md, tools/asn1grep.py, tools/requirements.txt
Added analyzers for whenever the UE provides an IMSI at all, or when a null cipher was set. Also, because I was having trouble finding which messages contained the `IMSI` datatype, I wrote a little python script that'll parse and search for datatypes in our ASN.1 files, and print any hits as a "path". For example:
```
» python asn1grep.py IMSI                                  
searching for IMSI
PCCH-Message [message [message.c1 [c1 [c1.paging [paging [pagingRecordList[0] [ [ue-Identity [ue-Identity.imsi [IMSI]]]]]]]]]]
```
=> IMSI provided + null cipher analyzer

Cargo.lock, bin/Cargo.toml, bin/src/qmdl_store.rs, dist/install-common.sh, lib/src/analysis/null_cipher.rs, serial/src/main.rs
Fixes the release process by waiting for `atfwd_daemon` to startup before running any AT commands.
Also some minor fixes/updates.
=> Fix release

bin/src/check.rs, lib/src/analysis/analyzer.rs
This makes the rayhunter-check output a lot more legible
=> rayhunter-check improvements

.github/workflows/build-release.yml, bin/src/analysis.rs, bin/src/check.rs, bin/src/config.rs, bin/src/daemon.rs, bin/src/diag.rs, bin/src/dummy_analyzer.rs, bin/src/error.rs, bin/src/pcap.rs, bin/src/qmdl_store.rs, bin/src/server.rs, bin/static/index.html, bin/static/js/main.js, dist/config.toml.example, lib/Cargo.toml, lib/src/analysis/analyzer.rs, lib/src/lib.rs
* rayhunter-daemon: API for triggering and reading analysis
* rayhunter-daemon: rename readonly mode to debug mode
* rayhunter-daemon: debug mode allows live-loading frontend files
* rayhunter-check: rework to handle directories
* rayhunter-check: better output
* CI: build rayhunter-check
=> On-demand analysis of past recordings

serial/src/main.rs
Without doing this, it seems macOS can't use any interface endpoints. Also disconnect any kernel extensions that're using the interface, since that can cause issues on macOS as well.
Fixes #55
=> serial: claim USB interface

dist/install-common.sh
With the odd permissions issues we've been seeing, we should use AT_SYSCMD for all mv operations into /data
=> fix installer script

bin/src/config.rs, bin/src/daemon.rs, bin/src/diag.rs, bin/src/framebuffer.rs, bin/src/server.rs, dist/config.toml.example
=> implement colorblind mode

serial/src/main.rs
=> serial: fix UTF-8 panic on macOS

lib/src/diag.rs, lib/src/gsmtap.rs, lib/src/gsmtap_parser.rs
=> lib: set uplink flag for NAS

README.md, dist/install-linux.sh, dist/install-mac.sh
* Small updates to documentation and install scripts 
* Fixes #94
=> Improve docs

tools/requirements.txt
nasparse.py and nasparse_test.py require the pycrate_mobile and pycrate_core libraries provided by the pycrate package.
This commit adds the required package to requirements.txt.
=> fix(tools): add pycrate dependency to requirements.txt

.cargo/config.toml
This commit enables various compile options to reduce the binary file size to fit on hardware with smaller filesystems.
See the recommendations of https://github.com/johnthagen/min-sized-rust
Applying reduces the binary size of the `rayhunter_daemon` by ~60%. (11619420 bytes ->  4614596 bytes).
Please verify if the optimizations still produce a working binary on actual hardware.
=> minimized the binary size

Cargo.lock, bin/Cargo.toml, bin/src/qmdl_store.rs, lib/Cargo.toml, lib/src/analysis/analyzer.rs, lib/src/lib.rs, lib/src/pcap.rs, lib/src/util.rs
Add the compile-time name and version to the pcap's Section Header Block as the shb_userappl option, the canonical place for storing the name of the application used to create the pcap.[0]
[0] https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcapng.html#section-4.1-10
Addresses issue #146 
Note: Because https://github.com/EFForg/rayhunter/blob/main/lib/Cargo.toml#L3 hasn't been updated with each release, it still reads `0.1.0`. Same for rayhunter-daemon's cargo manifest.
It may be worth plumbing the version number in a different way. (e.g., should this be the rayhunter lib's version number or the daemon's? I'm inclined to think the lib, but that's just my 2¢)
It may also be worth adding the operating system and particularly the hardware field. I can happily do …
=> feat(pcap): add rayhunter name and version to metadata

dist/install.sh
The `serial-macos-latest/serial` command in the installer bundle has the quarantine bit set. This unsets that attribute so that macOS doesn't throw an error message like
> “serial” Not Opened: Apple could not verify “serial” is free of malware that may harm your Mac or compromise your privacy.
This is the same error message @jullrich saw in #149. This fixes it. After the change, the installer script runs to completion on my M2 MacBook Air running macOS 15.3.2.
=> Remove the quarantine bit from the serial command on macOS

lib/src/analysis/analyzer.rs
Due to an upstream hampi bug (https://github.com/ystero-dev/hampi/issues/133), our RRC parser is reporting false-positives for the null cipher heuristic.
=> lib: diable null-cipher heuristic due to false positives

bin/src/daemon.rs, bin/src/qmdl_store.rs
If rayhunter doesn't exit cleanly (e.g. during a battery outage), the QMDL manifest may end up in a corrupted state. If that's the case, rayhunter should try to recover by creating a new manifest. This'll let it continue, and will preserve previous recordings, but they won't be visible through the UI.
Fixes #151
=> daemon: if we fail to parse the QMDL manifest, make a new one

Cargo.lock, serial/Cargo.toml, serial/src/main.rs
nusb is a pure Rust library providing the same low level access to USB devices as rusb/libusb.
This branch removes rusb (and thus the dependence on libusb) and replaces it with nusb in the serial utility.
Addresses https://github.com/EFForg/rayhunter/issues/176
=> refactor(serial): replace rusb with nusb

lib/Cargo.toml, rootshell/Cargo.toml, serial/Cargo.toml, telcom-parser/Cargo.toml
Don't forget these! The lib one is what's printed in pcap files, for example.
=> chore: bump all Cargo.toml versions to 0.2.6

lib/src/analysis/analyzer.rs
e79dc4a commented out the one usage of NullCipherAnalyzer but didn't remove the import, causing a compiler warning.
=> Remove unused import due to e79dc4a

README.md
Added this text to the FAQ to explain to users to access the device filesystem using the pre-built rootshell. 
```### How do I delete capture files from the Rayhunter device?
You can get a shell on the device by inputting `adb shell` to a terminal with the device connected, you can check if it is detected with `adb devices`.
The capture files are located at */data/rayhunter/qmdl* but you will need root access to modify or delete them. From the adb shell run `/bin/rootshell` and you can now use commands like 'rm' as root to modify and delete entries in the */data/rayhunter/qmdl* directory. **Be careful not to delete important files in other directories as you may seriously damage the device**.```
=> Added FAQ entry on how to use the rootshell to delete data from the device

Cargo.lock, serial/Cargo.toml, serial/src/main.rs
This branch adds better error handling and reporting to the serial binary with the following changes:
Support -h and --help arguments.
Print a better error message when the Orbic device is not found.
Replace every panic! with anyhow::bail!
Replace .expect() with .context()?
Wraps all function returns with anyhow::Result
Addresses #231 #88
=> feat(serial): replace all panics with error handling from anyhow

bin/src/qmdl_store.rs
Fix https://github.com/EFForg/rayhunter/issues/199
Fix https://github.com/EFForg/rayhunter/issues/151
rayhunter updates manifest files using write **without truncation**.
This means that if the new manifest is shorter than the old one,
trailing bytes of the old data will persist in the new file.
Switch over to atomic file writes so that this bug is fixed + rayhunter
behaves correctly if it is killed mid-write.
The changes in `RecordingStore::create` are just to ensure that all
writing of the manifest goes through `write_manifest`.
https://github.com/EFForg/rayhunter/pull/182 could be reverted as it
seems to mostly be a workaround.
=> Fix malformed QMDL manifest writes

bin/static/index.html, bin/static/js/main.js
* last_message_time is shown inconsistently for current entry vs other
entries -- deduplicate code
* last_message_time is N/A for undefined -- but the API response was
null instead of undefined, rendering Jan 01 1970 instead of N/A:
=> Fix rendering of last_message_time in UI

bin/src/daemon.rs, bin/src/diag.rs, bin/src/qmdl_store.rs, bin/static/index.html, bin/static/js/main.js
This PR adds a delete button to each row of the recordings table and a delete all button along side the start and stop buttons. The delete all button asks for confirmation before deleting, the row delete buttons do now.
I believe someone else was working on a revamp of the web ui, but I was able to throw this together in an evening, so we can have the feature while we wait.
Fixes #191
=> Add delete buttons to web ui

Cargo.lock, bin/Cargo.toml
This removes a bunch of dependencies we aren't using and reduces the binary size by 0.7 MB.
=> Remove unneeded image dependencies

.github/workflows/build-release.yml, dist/install.sh
This branch builds the serial binary, rayhunter-check, and install.sh for Linux on arm64.
=> ci: installer for ubuntu-24.04-arm (aarch64)

bin/src/daemon.rs, bin/src/diag.rs, bin/src/framebuffer.rs, bin/src/server.rs
Colorblind mode is a property of the respective display, and decision
whether to display something in colorblind mode should lie with the
display thread. The display thread already needs to know about
colorblind mode for the initial state.
In #226, there are multiple implementations of display thread, and at
least one of them is dealing with a one-bit display anyway.
Aside, I think rayhunter should send an initial DisplayState on startup,
UI threads should not assume that the device is already recording. But
this can be discussed separately.
=> Remove RecordingCBM

rootshell/src/main.rs
=> Indent rootshell's code to 4 space like everything else

.github/workflows/build-release.yml, .github/workflows/check-and-test.yml, lib/src/lib.rs, lib/src/util.rs, serial/src/main.rs
This branch builds the serial binary and rayhunter-check on Windows.
This branch modifies the serial binary, lib's RuntimeMetadata::new(), and conditionally builds lib/diag_device.rs in order to build those artifacts for Windows.
=> [WIP: needs install.bat] ci: add windows installer

.github/workflows/build-release.yml
should actually fix the builds in `main`
Waiting on tests in https://github.com/oopsbagel/rayhunter/actions/runs/14409018133 before marking ready for review.
=> ci(windows): compile serial for x86_64-pc-windows-gnu

README.md
The current `release.tar` (v0.2.7)  lacks a `release` directory -- all files live at the root of the tar archive. But the README's Unzip instructions mention `cd`ing to `~/Downloads/release`, which implies that there is a `release` directory inside the tar.
Rather than verify with `tar --list --file ~/Downloads/release.tar` I made a bad assumption, ran `tar xvf ./release.tar` in my `~/Downloads`, and then had to clean up my `~/Downloads` directory.
This update clarifies that users should create the directory and extract the tar into that directory.
- NA ~~[ ] Code has been linted and run through `cargo fmt`~~
=> README: clarify "unzip" instructions

.cargo/config.toml, .github/workflows/build-release.yml, README.md, lib/src/diag_device.rs, make.sh, tools/devenv.dockerfile, tools/run-docker-devenv
Aims to solve "I can't build on $platform".
Removes dependency on gcc-based cross-compilation toolchain.
This branch allows development on any machine that can install rustup toolchains. No special debian packages are needed to build any of the binaries, only what's installed by rustup.
Updates `.cargo/config.toml`, `make.sh`, tools/devenv, github actions, and the README to use the musl/rust-lld targets.
=> ci: use rust-lld for all release targets

.github/workflows/check-and-test.yml, Cargo.lock, lib/Cargo.toml, lib/src/diag.rs, lib/src/diag_device.rs
Old version of deku was throwing clippy lints in generated code
=> Fix clippy lints and upgrade deku

.github/workflows/mdbook.yaml, .gitignore, book.toml, doc/SUMMARY.md, doc/installation.md, doc/supported_devices.md
This branch adds an mdbook for rayhunter documentation in `doc`, and actions workflows to publish that documentation to github pages.
This branch configures actions to publish to pages via artifact uploads, but can be adjusted to publish based solely on a branch.[0] This was chosen to allow for future flexibility in generating multiple outputs (such as a single page html document or pdf).
[0] https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
=> docs: publish mdbook in doc to github pages

README.md
I had to do this on each new machine I built rayhunter on so I figure other people are gonna need it too. Without it, npm fails to run `vite build`.
=> doc(building bin/web): also run npm install

doc/installing-from-source.md, installer/build.rs, installer/src/orbic.rs
Due to recent build changes, --release no longer applies the right
optimization settings, and --profile firmware has to be used.
=> Fix installing from source

doc/tplink-m7350.md, doc/uninstalling.md, installer/src/main.rs, installer/src/tplink.rs, lib/src/diag_device.rs
* Fix autostart by adding another port trigger for rayhunter-daemon
* Use Orbic's IOCTL params as fallback
* Fix sdcard path and make it configurable
* Update docs to indicate support
* Add uninstalling instructions for TP-Link
Fix #325
=> Fixes for TP-Link M7350 v9

Cargo.lock, installer/Cargo.toml, installer/src/orbic.rs
This PR attempts to fix the issues on Windows with the serial and adb code both trying to claim the same USB interface by having them both use a shared USB claim.
=> Move most serial commands to usb shared USB claim with adb

bin/src/diag.rs, installer/src/orbic.rs
Due to a refactor in https://github.com/EFForg/rayhunter/pull/350, we
had to move more into the shared codepath of StopRecording. The todo!()
used to be unreachable when it was just in the stop-recording endpoint.
Fix #367
=> Fix crash when deleting recordings

.github/workflows/main.yml
I apparently don't know how this works.
=> ci: don't try to use env:

doc/faq.md
=> doc: add re-enabling USB tethering to the FAQ

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yaml
A lot of the bug report we receive are about the web UI or the installer
failing, and there things like capture date just don't matter. We could
create separate templates for these types of bugs, but I'd think it's
probably better to just have one textbox with a few "reminder" questions
that are all optional and can be removed entirely if they don't make sense.
We could also make all form fields in the template optional, but the
resulting issues would be cluttered with N/A.
Feature request template I think doesn't have this issue.
Also allow the creation of blank issues, because some issues are more
related to CI or devenv and don't neatly fit in any category. Let's just
hope nobody abuses that?
=> Loosen up issue templates

.github/workflows/main.yml
Documentation was being pushed from an unrelated PR that I opened,
because that PR was created from a branch pushed to efforg instead of my
own fork.
Right now the docs changes in #390 are live for everybody to see.
=> Do not publish docs from any branch

doc/SUMMARY.md, doc/supported-devices.md, doc/tplink-m7310.md, installer/src/tplink.rs
The device is very similar to the M7350, and might as well just be
another hardware version. The exploit for M7350 v3 works for M7310,
all I had to do is to change the URL slightly. So now the installer
tries both URLs.
=> Add support for TP-Link M7310

.github/workflows/main.yml
This is required to call this workflow from another workflow, such as the release.yml workflow.
=> fix(ci): restore deleted workflow_call trigger

bin/web/src/lib/components/ManifestCard.svelte, bin/web/src/lib/components/ManifestTableRow.svelte, bin/web/src/lib/manifest.svelte.ts
This is the same bug as #224, but regressed in the new UI
=> Fix last_message_time showing as 1970 when capture is 0 bytes

.github/workflows/main.yml, Cargo.lock, bin/Cargo.toml, bin/src/display/mod.rs, bin/src/display/wingtech.rs, installer/Cargo.toml, installer/build.rs, installer/src/main.rs, installer/src/orbic.rs, installer/src/tplink.rs, installer/src/util.rs, installer/src/wingtech.rs, lib/Cargo.toml
Add support for the Wingtech CT2MHS01 hotspot, a Qualcomm mdm9650-based device with a screen available for US$15-35. This device is often used as a base platform for white labeled versions like the T-Mobile TMOHS1. AT&T branded versions of the hotspot seem to be the most abundant.
The device has a framebuffer-driven screen at /dev/fb0 that behaves similarly to the Orbic RC400L, although the userspace program `displaygui` refreshes the screen significantly more often than on the Orbic. This causes the green line on the screen to subtly flicker and only be displayed during some frames. Subsequent work to fully control the display without removing the OEM interface is desired.
=> feat: support Wingtech CT2MHS01 hotspot

installer/src/tplink.rs
TP-Link v9 was inadvertently broken via https://github.com/EFForg/rayhunter/pull/390
=> Fix broken installer on TP-Link M7350 v9

book.toml, doc/SUMMARY.md, doc/configuration.md, doc/heuristics.md, doc/installing-from-release-windows.md, doc/installing-from-release.md, doc/introduction.md, doc/orbic.md, doc/tplink-m7350.md, doc/using-rayhunter.md
* Add a new configuration page and move content out from TP-Link. The
Configuration section in TP-Link is duplicating what is already in
config.toml.example, and given that we have recently added a lot of
new options I don't want to maintain multiple copies.
* Lots of anchor links were broken since we moved docs from README into
mdbook. Fix them all ~and shamelessly plug my own GitHub action to
prevent that from happening again (mdbook does not seem to have
anything builtin)~
* Document that the key input feature is disabled since 0.4.0.
* Smaller cosmetic changes:
* Make TP-Link M7350 page consistent with TP-Link M7310 page.
* Fix indentation on some bullet points.
* Center-align the rayhunter logo in introduction.md to calm my soul.
It is still misaligned with the page title above …
=> Update documentation and fix broken links

Cargo.lock, bin/Cargo.toml, bin/src/daemon.rs, bin/src/pcap.rs, bin/src/server.rs, bin/web/src/lib/components/ManifestCard.svelte, bin/web/src/lib/components/ManifestTable.svelte, bin/web/src/lib/components/ManifestTableRow.svelte, bin/web/src/lib/manifest.svelte.ts
fix #409 
don't know what to do with the other buttons. just remove?
=> Add ZIP download endpoint

Cargo.lock, telcom-parser/Cargo.toml
It's not clear for how long this revision will exist upstream now that
the PR is (squash) merged
=> Bump hampi to 0.7.1

.github/workflows/main.yml, bin/src/analysis.rs, bin/src/check.rs, bin/src/daemon.rs, bin/src/diag.rs, bin/src/display/tplink_framebuffer.rs, bin/src/display/tplink_onebit.rs, bin/src/key_input.rs, bin/src/pcap.rs, bin/src/server.rs, bin/src/stats.rs, lib/src/analysis/analyzer.rs, lib/src/analysis/connection_redirect_downgrade.rs, lib/src/analysis/imsi_requested.rs, lib/src/diag_device.rs, lib/src/gsmtap_parser.rs
These are almost entirely just moving variables into format strings. There are two left unfixed, both function calls with two many arguments.
Also fixes the two lint errors that were previously going to be fixed in #425.
=> Re-enable clippy build failures and clean up complaints

.cargo/config.toml, .github/workflows/main.yml
rustc -C strip=debuginfo leaves the symbol table intact, meaning RUST_BACKTRACE=1 on the installer still produces helpful output.
This significantly reduces the binary size, eg the amd64 installer goes from 93M to 21M. Stripping the symbol table only reclaims a further ~2M.
```
% RUST_BACKTRACE=1 ./target/release/installer wingtech --admin-password 1234
Starting telnet ... 
Failed to install rayhunter on the Wingtech CT2MHS01
Caused by:
0: error sending request
1: client error (Connect)
2: tcp connect error
3: Network is unreachable (os error 101)
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
1: installer::wingtech::run_command::{{closure}}
2: installer::run::{{closure}}
3: tokio::runtime::park::CachedParkThread::block_on
4: …
```
=> cargo/config: strip debuginfo from --release bins for a significantly smaller installer size

.cargo/config.toml, Cargo.lock, installer/Cargo.toml
Example release build of `-p installer` with NO_FIRMWARE_BIN on amd64 linux, after `cargo clean --release`:
Before (default lto and opt-levels):
```
Finished `release` profile [optimized + debuginfo] target(s) in 2m 18s
7.8M    ./target/release/installer
```
fat lto, default opt level:
```
Finished `release` profile [optimized + debuginfo] target(s) in 2m 12s
5.6M    ./target/release/installer
```
opt-level z and fat lto:
```
Finished `release` profile [optimized + debuginfo] target(s) in 1m 39s
4.7M    ./target/release/installer
```
TODO:
rayhunter-check benchmarks may inform whether opt-level z introduces a performance hit. Fat LTO is expected to be a performance increase.
There's no reason why rayhunter-check and the installer have to be compiled with the same settings if they need to …
=> Smaller installer

doc/installing-from-release-windows.md, doc/installing-from-release.md, doc/installing-from-source.md, doc/introduction.md, doc/orbic.md, doc/tplink-m7350.md, doc/updating-rayhunter.md, doc/wingtech-ct2mhs01.md
The PR adds miscellaneous small documentation fixes.
Fixes some typos like misspellings or missing code blocks.
Standardizes references to the software and project as **R**ayhunter (with a capital R).
Rayhunter standardization does not change any paths or commands where casing matters.
=> docs: misc typo fixes

installer/src/main.rs, installer/src/util.rs
Since we never turn on ADB, it's a bit cumbersome to send files to the
device.
=> Add send-file utilities for wingtech and tplink

.cargo/config.toml, .github/workflows/main.yml, doc/installing-from-release.md, doc/installing-from-source.md
Support installing on aarch32/armv7 linux systems, such as 32bit raspberry pis and beaglebones.
This branch changes the installer names from "ubuntu" to "linux", as they are statically linked and not dependent on any particular linux distribution.
=> ci: build installer and rayhunter-check for armv7, rename ubuntu -> linux in release bundles

installer/Cargo.toml, installer/src/main.rs
Slightly reduce binary size by using the smaller 'rt' feature and the current_thread runtime flavor in the installer, since there is no benefit to true multithreading.
This also gives a small compile time boost on my system.
=> installer: tokio runtime flavor current_thread

.github/workflows/main.yml, daemon/Cargo.toml, daemon/src/display/mod.rs, daemon/src/display/tmobile.rs, doc/SUMMARY.md, doc/supported-devices.md, doc/tmobile-tmohs1.md, installer/build.rs, installer/src/main.rs, installer/src/tmobile.rs, installer/src/util.rs, installer/src/wingtech.rs, lib/Cargo.toml
Add support for the Tmobile TMOHS1, a Wingtech CT2MHS01-based hotspot with a Qualcomm mdm9607. The TMOHS1 has no screen, only 5 LEDs, two of which are RGB.
This pull request is a draft until https://github.com/EFForg/rayhunter/pull/387 is merged, because it uses common installer code and makes modifications to some of the same files (like `display/src/mod.rs`).
I will refactor out some of the other commonalities in the installer between this and the Wingtech before merging.
=> feat: support Tmobile TMOHS1 hotspot

check/src/main.rs, lib/src/analysis/imsi_requested.rs
Complete rewrite of the IMSI requested heuristic, instead of warning every time we send the IMSI (which leads to some false positives if an authentication happens or on first power) we instead keep track of the state and warn about strange states such is identity request which is not followed with authentication or an identity request which isn't preceded by an attach request. This greatly reduces false positives.
=> Imsi request v2

Cargo.lock, daemon/src/display/headless.rs, daemon/src/display/mod.rs, daemon/src/main.rs, doc/SUMMARY.md, doc/pinephone.md, doc/supported-devices.md, installer/Cargo.toml, installer/src/main.rs, installer/src/orbic.rs, installer/src/pinephone.rs, installer/src/util.rs, lib/src/lib.rs
I have tested this on the PinePhone 1.2 and PinePhone Pro successfully. Both contain the exact same modem with the exact same product ID. From the pine64 website, all of the PinePhone revisions (1.0, 1.1, &c) use the same modem, so this should work for all PinePhone products.
One of the big advantages to this is the device supports GNSS, making this a good choice for casual wardriving.
=> Support for running on the PinePhone's Quectel modem

Cargo.lock, daemon/Cargo.toml, daemon/src/display/generic_framebuffer.rs, daemon/src/display/orbic.rs, daemon/src/display/tmobile.rs, daemon/src/display/tplink.rs, daemon/src/display/tplink_framebuffer.rs, daemon/src/display/tplink_onebit.rs, daemon/src/display/wingtech.rs, daemon/src/main.rs
Rayhunter uses a mixture of spawn and spawn_blocking, then also does
some blocking operations inside of async code.
Move everything to async and enable the single-thread runtime.
Now the binary is 100kB smaller, and the memory usage also improved by
~100kB on tplink.
`spawn_blocking` can still be used from the single-threaded runtime
(it will just spawn more threads) but might negate the memory savings.
=> Remove blocking code and spawn_blocking

daemon/src/display/mod.rs, daemon/src/display/uz801.rs, daemon/src/main.rs, daemon/src/stats.rs, doc/SUMMARY.md, doc/supported-devices.md, doc/uninstalling.md, doc/uz801.md, installer/src/main.rs, installer/src/uz801.rs, lib/src/lib.rs
Added support for the UZ801 LTE modem platform. The installer is untested/incompletely tested/experimental, but I will do further work the moment that a second user who owns one of these devices pops up.
See https://github.com/EFForg/rayhunter/discussions/479.
=> Add UZ801 support

.github/workflows/main.yml, doc/SUMMARY.md, doc/moxee.md, doc/supported-devices.md, doc/wingtech-ct2mhs01.md, installer/src/main.rs, installer/src/orbic_network.rs, installer/src/tmobile.rs, installer/src/tplink.rs, installer/src/util.rs, installer/src/wingtech.rs
See https://github.com/EFForg/rayhunter/discussions/528
There is a shell injection vulnerability after all, so we can just
launch a remote shell, tplink-style. Except there's no telnetd on this
device so we need to use netcat.
This was found in the goahead binary on the device using Ghidra. The
decompiled code for this endpoint looks like this:
```c
void FUN_0003c614(int param_1)
{
int iVar1;
undefined4 uVar2;
int local_160;
undefined1 auStack_15c [64];
char acStack_11c [256];
int local_1c;
local_1c = __stack_chk_guard;
if (param_1 == 0) {
error("input parameter is NULL!");
uVar2 = 0x66;
goto LAB_0003c808;
}
iVar1 = websGetJsonItemValue(param_1,"password",10,auStack_15c,0x40);
if (iVar1 != 0) {
iVar1 = get_log_level_something();
if (1 < iVar1) {
some_logging_func(2,"modifying root …
```
=> Add a orbic network installer

daemon/web/src/lib/components/AnalysisTable.svelte
Each event index corresponds to an index in analyzers. But some events
may be null. We're skipping those events without incrementing the index,
leading to wrong analyzer names.
=> Fix wrong analyzer name in AnalysisTable

daemon/web/src/routes/+page.svelte
This will save bandwith and battery on the hotspot in cases where the UI tab is left open. See #564.
=> Skip updating web UI when browser tab isn't visible

daemon/web/src/lib/components/ActionErrors.svelte
It's a little silly to show the 1/1 error count:
So we hide it unless there is more than 1 error:
=> Hide error count in error toast if there is only 1 error

.github/workflows/main.yml, doc/installing-from-source.md
Running without -p can confuse cargo to enable the wrong set of
featureflags.
Fix #581
=> Always run all builds with -p

lib/src/analysis/test_analyzer.rs
Fixes 2 bugs in the test heuristic, documented in #580 and #562. Cell ID decoded correctly and handle 2 digit MNCs.
=> Fix 580 and 562

daemon/web/src/lib/components/AnalysisTable.svelte, daemon/web/src/lib/components/ManifestCard.svelte
Fixes a very minor UI issue introduced in #492 where scrollbars would always be shown, at least on Chrome on Linux (Firefox and I think MacOS are better about overriding the setting and hiding them). 
Before:
After:
=> Don't show scroll bars when no overflow

daemon/src/display/generic_framebuffer.rs, daemon/src/display/headless.rs, daemon/src/display/orbic.rs, daemon/src/display/tmobile.rs, daemon/src/display/tplink.rs, daemon/src/display/tplink_framebuffer.rs, daemon/src/display/tplink_onebit.rs, daemon/src/display/uz801.rs, daemon/src/display/wingtech.rs, daemon/src/key_input.rs, daemon/src/main.rs
My upcoming low battery notifications PR adds another thread that needs to be shutdown and this prevents me from having to create yet another oneshot pair.
=> Simplify shutdown with cancellation tokens

installer/src/tplink.rs
Correct the paths used during install to not assume an SDcard is present
=> installer: Fix TPLink install with --skip-sdcard

doc/installing-from-release.md
the first time i tried to install rayhunter, i did it through a usb hub and the installer failed. i then connected the hotspot directly to my computer without the hub and it worked just fine
i brought this up in a meeting at EFF about rayhunter where it was suggested we mention this as a troubleshooting step in case it helps someone else. not all usb devices are created equal and these few sentences could potentially save users from some otherwise painful debugging
=> suggest using a different usb connection when troubleshooting
